apiVersion: v2
name: universal-helm
description: A Helm chart for Kubernetes

keywords:
  - blockchain
  - web3

maintainers:
  - name: Sam
    email: samuel@upshot.xyz

type: application
version: 0.6.11
